"""
Django settings for college_management_system project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import dj_database_url
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a gitignored .env file (KEY=VALUE per line) into os.environ so local
# secrets like the SMTP password live in one file instead of having to be
# re-exported in every new terminal session. Real environment variables
# still win over the file.
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _key, _, _value = _line.partition('=')
            os.environ.setdefault(_key.strip(), _value.strip())


def _env_flag(name, default=False):
    """Read a boolean env var. Anything but the words below is a lie."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    """Comma-separated env var to a list, blanks dropped."""
    return [item.strip() for item in os.environ.get(name, '').split(',')
            if item.strip()]


# DEBUG follows the environment rather than a hardcoded True.
#
# The default is derived from whether this looks like a deployment at all: a
# managed database or Render's own marker means yes, and then DEBUG is off
# and a real SECRET_KEY is mandatory. A bare `manage.py runserver` or
# `manage.py test` on a laptop has neither, so it still works with no setup —
# which is the only reason this isn't simply `default=False`.
# DJANGO_DEBUG overrides either way, and the Render blueprint sets it
# explicitly rather than trusting this inference.
_looks_deployed = bool(os.environ.get('DATABASE_URL')
                       or os.environ.get('RENDER'))
DEBUG = _env_flag('DJANGO_DEBUG', default=not _looks_deployed)

# SECURITY WARNING: keep the secret key used in production secret.
#
# The old hardcoded key is gone, but it is still in this repository's history
# and must be treated as public forever. Generate a fresh one for any deployed
# instance and set it in the host's environment:
#
#   python -c "from django.core.management.utils import get_random_secret_key as k; print(k())"
#
# Development falls back to a fixed throwaway so `runserver` needs no setup;
# a deployment with DEBUG off has to supply its own or refuse to boot.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError(
            "DJANGO_SECRET_KEY must be set when DEBUG is off. Generate one "
            "with: python -c \"from django.core.management.utils import "
            "get_random_secret_key as k; print(k())\"")
    SECRET_KEY = 'dev-only-insecure-key-do-not-deploy-this'

# Hosts Django will answer to. Render supplies its own external hostname; add
# any custom domain to DJANGO_ALLOWED_HOSTS as well.
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    ALLOWED_HOSTS.append(_render_host)
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']

# Hosts whose forms may POST here. The React app is served from Vercel and
# reaches this backend through a Vercel rewrite, so the browser's Referer
# says vercel.app while the Host header says onrender.com — without this,
# Django 3.1's HTTPS referer check rejects every write.
# Host format, no scheme: Django 3.1 predates the scheme-qualified list.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Render terminates TLS at its proxy and forwards plain HTTP, so without this
# Django believes every request is insecure: it would refuse to set Secure
# cookies and would skip the referer check that CSRF_TRUSTED_ORIGINS feeds.
if _env_flag('DJANGO_BEHIND_TLS_PROXY', default=bool(_render_host)):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party Apps
    'rest_framework',

    # My Apps
    'main_app.apps.MainAppConfig'
]

# JSON API for the React frontend (main_app/api/, mounted at /api/v1/).
# Session-cookie auth: the Vite dev server proxies /api and /media to Django,
# so requests are same-origin and the sessionid/csrftoken cookies just work.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Unauthenticated requests must yield 401 (not DRF's default 403) so the
    # frontend's axios interceptor can trigger a re-login.
    'EXCEPTION_HANDLER': 'main_app.api.exceptions.api_exception_handler',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Directly after SecurityMiddleware, as WhiteNoise requires: a static file
    # should be answered and returned before session, auth and CSRF do work
    # that a .css file has no use for. It sat at the bottom of this list
    # before, which quietly meant every asset paid for all of that first.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'college_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['main_app/templates'], #My App Templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'college_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# SQLite is the development default and is overridden wholesale by
# DATABASE_URL further down (see the dj_database_url call at the end of this
# file). A deployed instance MUST set DATABASE_URL: hosts like Render and
# Vercel give each instance an ephemeral filesystem, so a SQLite file there
# is silently discarded on the next deploy along with everything written to
# it.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'django',
    #     'USER': os.environ.get('DB_USER'),
    #     'PASSWORD': os.environ.get('DB_PASS'),
    #     'HOST': '127.0.0.1',
    #     'PORT': '3307'
    # }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
#
# These used to be applied only when DEBUG was on, which was harmless while
# DEBUG was hardcoded True and became a hole the moment it wasn't: a deployed
# instance would have accepted "1234" as a student's password. They now apply
# everywhere. Students choose these passwords themselves through the
# email-verification link, so this is the only thing standing between the
# college's records and a guessable password.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

# The built React app (vite build, base '/static/') is collected into
# STATIC_ROOT alongside main_app's assets; its index.html is served by
# main_app.views.react_app.
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'frontend', 'dist')]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
AUTH_USER_MODEL = 'main_app.CustomUser'
AUTHENTICATION_BACKENDS = ['main_app.EmailBackend.EmailBackend']
TIME_ZONE = 'Asia/Kolkata'

# Session Configuration for Remember Me functionality
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds (default)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # This will be overridden by remember me
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request to extend expiry

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True

# Real SMTP only kicks in once credentials are supplied via env vars;
# otherwise emails just print to the runserver console (dev-friendly, and
# lets the verification-email link still be copy-pasted for testing).
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Py3.12+-compatible subclass of Django 3.1's SMTP backend.
    EMAIL_BACKEND = 'college_management_system.smtp_backend.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'College ERP <noreply@example.edu>')

# Base URL of the deployed React frontend, used to build links (e.g. the
# email-verification link) that are sent out in emails.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Which email domains are acceptable for accounts. For now everyone (admin,
# staff, student) may use any common personal provider or the college domain;
# tighten these lists later if you want staff/admin restricted to the
# institutional domain only.
ALLOWED_EMAIL_DOMAINS = [
    'gmail.com', 'outlook.com', 'hotmail.com', 'live.com',
    'yahoo.com', 'icloud.com', 'me.com', 'proton.me', 'protonmail.com',
    'ncit.edu.np',
]
STAFF_ALLOWED_EMAIL_DOMAINS = ALLOWED_EMAIL_DOMAINS
STUDENT_ALLOWED_EMAIL_DOMAINS = ALLOWED_EMAIL_DOMAINS
LIBRARIAN_ALLOWED_EMAIL_DOMAINS = ALLOWED_EMAIL_DOMAINS
ACCOUNTANT_ALLOWED_EMAIL_DOMAINS = ALLOWED_EMAIL_DOMAINS

# Non-manifest storage: Vite already content-hashes the React bundle, and the
# legacy AdminLTE plugin CSS has broken url() refs the manifest storage
# rejects at collectstatic time.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# DATABASE_URL wins over the SQLite default above when it is set, and is a
# no-op otherwise. Keyed off the URL alone, so switching the deployment's
# database is an environment change and never a code change.
prod_db = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(prod_db)
