# Generated by Django 3.1.1 on 2026-06-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
