# Generated by Django 3.1.1 on 2026-06-24 02:51

from django.db import migrations


def copy_semesters(apps, schema_editor):
    Subject = apps.get_model('main_app', 'Subject')
    CourseSubject = apps.get_model('main_app', 'CourseSubject')
    for subject in Subject.objects.all():
        for course in subject.courses.all():
            CourseSubject.objects.get_or_create(
                course=course,
                subject=subject,
                defaults={'semester': subject.semester},
            )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_coursesubject'),
    ]

    operations = [
        migrations.RunPython(copy_semesters, reverse_noop),
    ]
