# Generated by Django 3.1.1 on 2026-06-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_copy_course_subject_semesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        # The semester-per-course data already lives in CourseSubject (created
        # in 0004 and populated in 0005). Switching `courses` to a through M2M
        # is purely a state change for Django; the table is already in place.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='subject',
                    name='courses',
                    field=models.ManyToManyField(
                        related_name='subjects',
                        through='main_app.CourseSubject',
                        to='main_app.Course',
                    ),
                ),
            ],
            database_operations=[
                # Drop the now-orphaned implicit M2M join table.
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS main_app_subject_courses;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
