# Generated by Django 3.1.1 on 2026-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubject',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='course_subjects', to='main_app.Staff'),
        ),
    ]
