# Generated by Django 3.1.1 on 2026-06-24 09:55

from django.db import migrations


def copy_staff(apps, schema_editor):
    """Copy subject-level staff onto every course+subject row of that subject,
    preserving current behaviour as a starting point for per-course refinement."""
    Subject = apps.get_model('main_app', 'Subject')
    CourseSubject = apps.get_model('main_app', 'CourseSubject')
    for subject in Subject.objects.all():
        staff_ids = list(subject.staff.values_list('id', flat=True))
        if not staff_ids:
            continue
        for cs in CourseSubject.objects.filter(subject=subject):
            cs.staff.add(*staff_ids)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_coursesubject_staff'),
    ]

    operations = [
        migrations.RunPython(copy_staff, reverse_noop),
    ]
