# Generated by Django 3.1.1 on 2026-06-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_copy_subject_staff_to_coursesubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='staff',
        ),
    ]
