# Generated by Django 3.1.1 on 2026-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_subject_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('day', 'Day Shift')], default='morning', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('day', 'Day Shift')], default='morning', max_length=10),
        ),
    ]
