# Generated by Django 3.1.1 on 2026-06-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20260624_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='teaches_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='teaches_morning',
            field=models.BooleanField(default=True),
        ),
    ]
