# Generated by Django 3.1.1 on 2026-06-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20260624_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubject',
            name='staff',
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='day_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_assignments', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='morning_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_assignments', to='main_app.staff'),
        ),
    ]
