# Generated by Django 3.1.1 on 2026-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20260624_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
