# Generated by Django 3.1.1 on 2026-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_student_current_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
