# Generated by Django 3.1.1 on 2026-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_attendance_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='passed_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
