# Generated by Django 3.1.1 on 2026-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20260625_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
