# Generated by Django 3.1.1 on 2026-06-27 09:22

from django.db import migrations, models
import django.db.models.deletion


def backfill_course_semester(apps, schema_editor):
    """Set course + semester on existing attendance from its reports. The course
    comes from the students that were marked; the semester from the CourseSubject
    row linking that subject to that course. Records with no reports stay null."""
    Attendance = apps.get_model('main_app', 'Attendance')
    AttendanceReport = apps.get_model('main_app', 'AttendanceReport')
    CourseSubject = apps.get_model('main_app', 'CourseSubject')
    for att in Attendance.objects.all():
        report = AttendanceReport.objects.filter(attendance=att).select_related('student').first()
        if not report:
            continue
        course_id = report.student.course_id
        cs = CourseSubject.objects.filter(subject_id=att.subject_id, course_id=course_id).first()
        att.course_id = course_id
        att.semester = cs.semester if cs else None
        att.save(update_fields=['course', 'semester'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_course_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_course_semester, migrations.RunPython.noop),
    ]
