# Generated by Django 3.1.1 on 2026-07-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20260710_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='courses',
        ),
    ]
