# Generated by Django 3.1.1 on 2026-07-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_staff_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='course',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='final_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='internal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='pre_board',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='unit_test',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('student', 'subject', 'course', 'semester')},
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='test',
        ),
        migrations.CreateModel(
            name='ResultFinalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
            ],
            options={
                'unique_together': {('course', 'subject', 'semester')},
            },
        ),
    ]
