# Generated by Django 3.1.1 on 2026-07-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20260710_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('subject', 'course', 'semester', 'shift', 'date')},
        ),
    ]
