# Generated by Django 3.1.1 on 2026-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20260711_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email_approved',
            field=models.BooleanField(default=False),
        ),
    ]
