# Generated by Django 3.1.1 on 2026-08-07 05:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_customuser_pending_email_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Course code must be exactly 2 digits')], verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='session',
            name='batch_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}-\\d{2}-\\d{4}$', 'Registration number must be 12 digits formatted as YYYY-XX-XX-XXXX')]),
        ),
        migrations.CreateModel(
            name='RollNumberBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.session')),
            ],
            options={
                'verbose_name_plural': 'Roll number batches',
                'unique_together': {('session', 'course')},
            },
        ),
    ]
