# Generated by Django 3.1.1 on 2026-08-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_backfill_generated_identifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
