# Generated by Django 3.1.1 on 2026-08-07 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_issuedsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d$', 'Course code must be a single digit')], verbose_name='Course Code'),
        ),
    ]
