# Generated by Django 3.1.1 on 2026-08-07 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_shift_in_roll_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Position in the roll-number slot table (1-49).', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(49)], verbose_name='Course Code'),
        ),
    ]
