# Generated by Django 3.1.1 on 2026-08-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_library_borrow_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='due_date_before_renewal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='reminder_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='renewal_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='renewal_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_decisions', to='main_app.librarian'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='renewal_librarian_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='renewal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='renewal_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='renewal_state',
            field=models.CharField(choices=[('none', 'Not requested'), ('requested', 'Renewal requested'), ('granted', 'Renewed'), ('declined', 'Renewal declined')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='LibraryFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('paid', 'Paid in cash'), ('waived', 'Waived')], default='paid', max_length=6)),
                ('amount', models.PositiveIntegerField()),
                ('days_late', models.PositiveSmallIntegerField(default=0)),
                ('rate_per_day', models.PositiveSmallIntegerField(default=10)),
                ('collected_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_collected', to='main_app.librarian')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fine_records', to='main_app.bookrequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_fines', to='main_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='libraryfine',
            constraint=models.UniqueConstraint(fields=('request',), name='one_fine_record_per_loan'),
        ),
    ]
