# Generated by Django 3.1.1 on 2026-08-09 05:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_library_renewal_and_fines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountant_id', models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Accountant ID must be exactly 6 digits')])),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Librarian'), (5, 'Accountant')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online transfer'), ('cheque', 'Cheque'), ('bank', 'Bank deposit')], default='cash', max_length=6)),
                ('collected_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to='main_app.accountant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='main_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accountant',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='main_app.course')),
            ],
            options={
                'ordering': ['course', 'semester'],
                'unique_together': {('course', 'semester')},
            },
        ),
    ]
