# Generated by Django 3.1.1 on 2026-08-09 00:43

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_fees_and_accountant_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposited_on', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=main_app.models.deposit_slip_path)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('reviewed_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slips', to='main_app.feeinvoice')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slip', to='main_app.feepayment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips_reviewed', to='main_app.accountant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_slips', to='main_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='depositslip',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, status='rejected'), fields=('invoice', 'reference'), name='one_live_slip_per_invoice_reference'),
        ),
    ]
